### ISSUE TITLE
Have multiple animations active at same time

### ISSUE THREAD

**Issue by bobby3572** [chazzu/hass-animated-scenes#1]
Hello....    just installed this into HASS and I really like how it works.    Right now it seems like it basically supports changing a set of lights through a series of color/brightness steps.    Very useful but it would be great if I could also:

1) have the ability to set different lights to different color/brightness scenes within the same animation....   so like light A = red, light B = blue etc where red and blue are separate queues of color rotation
2) have the ability to have multiple animations running at once.   Right now when I turn on one, it deactivates the last one.   Is there any way to have them act independently?   (if so then that might actually solve #1)

Let me know if there is a way to do this please.    Thanks!!

**Comment by chazzu** [comment]
Apologies, I am paying attention to this project I just took a vacation from emails for the holidays.

Specifying colors per-light seems tedious but potentially useful. What if instead, though, I allowed 'light groups' A light group could have one light, or multiple, so you can specify one or more lights to have specific colors. I think this would be more flexible and potentially less tedious in some situations.

The intention behind stopping other 'scenes' is to prevent conflicts. However, I'm thinking I could add a feature such that you can specify a 'conflicting scenes' option. Any scenes there will be shut off when the configured scene is activated; if you specify the option with nothing under it then it won't stop other scenes. There's already an option to specify other switches to turn off, so I can just integrate it that way.

Think that would cover what you're looking for?

**Comment by bobby3572** [comment]
Thanks for the reply.    Yes I think it would.   So basically I could set it up such different groups have different automations?    That would be great!


Harley

**Comment by Silverline69** [comment]
bump

**Comment by zSprawl** [comment]
I really like this addon. I hope you get an renewed interest in it this holiday season. :)

**Comment by chazzu** [comment]
@zSprawl @Silverline69 @bobby3572 I am working on some broad changes. The switch integration will stay as-is for now, but I am working on a new service-based method which will allow multiple animations at the same time and editing via the interface with blueprints. This would also allow for animation groups, essentially. If there are any other ideas for improvements, now would be a great time to let me know.
No ETA yet, but I have the initial configuration up and running and will be creating a new branch for this by next month if anyone wants to help me test. I'm still limited on time, but my plan is to finish these improvements by summer. 
Thank you for your patience.

**Comment by chazzu** [comment]
V1 should now support multiple animations. Please report any issues. Closing this issue.
