### ISSUE TITLE
not looping

### ISSUE THREAD

**Issue by mortalone** [chazzu/hass-animated-scenes#10]
Hi. i am trying to set up this script. but i am unable to get it to run a loop.

if i set it up in automations on a time pattern for 5seconds (example). i have to use toggle. in order for it to change color. if i just activate the switch. it just selects a color and stays on that color.

if i create a lovelace szitch button. it stays on that color.

what am i doing wrong ?

**Comment by bjornsivertsen** [comment]
Post your Switch and configuration.yaml code that concerns animated scenes.

For reference, I have a working setup that looks like this:

configuration.yaml:
`animated_scenes:`

switch.yaml:
`  - platform: animated_scenes
    name: Lovely Scene
    lights:
      - light.living_room_floor_lamp
      - light.living_room_table_lamp
      - light.dining_room_table_lamp1
      - light.dining_room_table_lamp2
      - light.dining_room_pendant
      - light.bedroom_pendant
      - light.hall_pendant
      - light.dining_room_strip
      
    brightness: [200, 255]
    colors:
      - color_type: rgb_color
        color: [ 255, 113, 206 ]
        one_change_per_tick: False
      - color_type: rgb_color
        color: [ 1, 205, 254 ]
        one_change_per_tick: False
      - color_type: rgb_color
        color: [ 5, 255, 161 ]
        one_change_per_tick: False
      - color_type: rgb_color
        color: [ 185, 103, 255 ]
        one_change_per_tick: False
      - color_type: rgb_color
        color: [ 255, 251, 150 ]
        one_change_per_tick: False
    transition: 15
    change_frequency: 60
    change_amount: all`

lovelace:
`type: button
tap_action:
  action: toggle
entity: switch.animated_scene_lovely_scene
name: Lovely
icon: hass:flower`

**Comment by mortalone** [comment]
so i used your code for the switch. and that worked. thank you very much.

i had just copied the code from the example.

im not sure what part did not work. but i would like to try to play with the diffrent settings.

`  - platform: animated_scenes
    name: Spooky Scene
    lights:
      - light.upspot_pa_birketra_venstre_level_light_color_on_off
      - light.upspot_pa_birketra_hojre_level_light_color_on_off
    brightness: [100, 255]
    colors:
      - color_type: rgb_color
        color: [ 247, 95, 28 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 255, 154, 0 ]
        one_change_per_tick: True
        weight: 5
      - color_type: rgb_color
        color: [ 136, 30, 228 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 133, 226, 31 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 148,0,211 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 200, 10, 10 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 135, 169, 107 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 103, 76, 71 ]
        one_change_per_tick: True
    transition: [1, 4]
    change_frequency: 5
    change_amount: 6`

**Comment by bjornsivertsen** [comment]
If you want all the lights to follow the same pattern, create a light group that you call instead of the individual 2 lights.

This is what I do with light.dining_room_pendant, which actually covers 2 lamps above my dining table.

**Comment by mortalone** [comment]
oh. yes. obviously :)
 thank you. i wes too focused on some setting in the yaml script.
