### ISSUE TITLE
Publish this repo to HACS

### ISSUE THREAD

**Issue by bjornsivertsen** [chazzu/hass-animated-scenes#13]
It would be fantastic if the repo could be published to HACS, so eventual updates would be managed through there.

Steps are described here:
https://hacs.xyz/docs/publish/start

**Comment by d8ahazard** [comment]
@chazzu - I've actually got most of this set up locally, want me to submit a PR with the updated structure and files?

**Comment by chazzu** [comment]
That would definitely be appreciated.

**Comment by d8ahazard** [comment]
> That would definitely be appreciated.

See #14

**Comment by Fidelity88** [comment]
Just wanted to add my comment here too:
Might I suggest adding this in the [README.MD](https://github.com/chazzu/hass-animated-scenes/blob/master/README.MD) file? I was searching on how to add this as a repo, but had to search through the Issues to figure out how to
