### ISSUE TITLE
Problem with Example

### ISSUE THREAD

**Issue by zSprawl** [chazzu/hass-animated-scenes#15]
Just wanted to drop a note that I had a lot of problems with the example, and Googling led to others with the same issue. It seems the problems are in your example with the line:

change_amount: 6

It really needs to be:

change_amount: all

**Comment by fdorssers** [comment]
Just installed this and copied up the "Spooky Scene" example, added five lights, and made sure that the `change_amoung` was equal to, or less than, the amount of lights I'd configured. And it's working great at the moment. Could it be that there weren't at least six lights configured?

**Comment by lgwapnitsky** [comment]
Tried the above with my Tuya lights (not running Tuya Local, yet), and getting zero results. Just regular lights

**Comment by chazzu** [comment]
@lgwapnitsky Did you discover anything further? #16 also mentions issues with Tuya, but I do not have Tuya to test with.

**Comment by chazzu** [comment]
For now, I am closing this as it is covered by #16 . I am adding RGBW and RGBWW support, and from some cursory Googling I think that will resolve the issue with Tuya. #16 will be updated when that change is completed and available to test.
