### ISSUE TITLE
Feature request - sensor where state is count of running animations and has attributes with details about the running ones

### ISSUE THREAD

**Issue by finder39** [chazzu/hass-animated-scenes#22]
I think it could be really useful to have a sensor added to home assistant that shows the number of Animated Scenes running, and container an attribute with a dictionary/array of the names of the Animated Scenes and the lights they're working with.

This could come in handle for a couple things:
- When running a "goodnight" or "end of day refresh" script, this could be used to make sure all Animated Scenes are stopped
- There are some automations that I (and I'm sure others) have created to sync light switch status LED bars to the brightness of hue or other lights. (useful for Inovelli Blue switches which have an LED bar to show light brightness. We could use this to know which ones to temporarily ignore since the brightness could be constantly changing and don't want to flood the zigbee network or overload HA with constant changes

**Comment by chazzu** [comment]
I have added a sensor as requested in the latest release, #26 
Can you please let me know if you encounter any issues?
