### ISSUE TITLE
Restore State doesn't restore correct color temp

### ISSUE THREAD

**Issue by DarkTearStudios** [chazzu/hass-animated-scenes#27]
If my lights were white before starting the animation, restoring it after stopping the animation sets it to the rgb equivalent of the temperature it was at prior, for example if it was at 2700k it "restores" it to 255, 169, 87. I have the automation set to rgbw_color

**Comment by chazzu** [comment]
@DarkTearStudios Can you update to the latest version in HACS and report back? I cannot duplicate the issue on my end, maybe different lights or something, but I did make a change that I think might resolve the problem. Before, I was just grabbing a color out of a list of attributes when restoring the light, now I'm explicitly restoring the prior color mode.

**Comment by DarkTearStudios** [comment]
I appreciate the response! Unfortunately with the update, after stopping the animation its now not restoring at all, and breaking it altogether, so have to restart to use it again. when i stop im now getting this error: 
Error while executing automation automation.candle_off: extra keys not allowed @ data['color_mode']

**Comment by chazzu** [comment]
Whoops. @DarkTearStudios I just pushed a new release 1.1.2 that should fix that. Thanks for catching it so quick.

**Comment by DarkTearStudios** [comment]
Holy wow! your quick. This did the trick and completely fixed everything. Thank you!!
