### ISSUE TITLE
Share some more example scenes

### ISSUE THREAD

**Issue by fluxor99232** [chazzu/hass-animated-scenes#38]
Does anyone have some more example scenes to share? Maybe even efforts to imitate some of the dynamic Philips Hue scenes? Would be very interested in seeing what you have created and would also help me getting started.

Found the tip to use scripts and parameters for rooms shared in issue #34 very helpful! Would probably help a lot of people adding that to the documentation.

**Comment by chazzu** [comment]
I was thinking of sharing some more examples on the readme, but I didn't want to clutter it anymore. After reading your suggestion, I've added some to the wiki:

https://github.com/chazzu/hass-animated-scenes/wiki/Shared-Animations

If you have any animations you want to share., let me know and I'll happily add them.

**Comment by fluxor99232** [comment]
Wow, thank you so much! Installed them all right away!
