### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'animated_scenes'. 

### ISSUE THREAD

**Issue by jmtatsch** [chazzu/hass-animated-scenes#4]
As of Home Assistant 2021.6, this integration will no longer be loaded.
Please report this to the maintainer of 'animated_scenes'.
Just leaving this here.
Should be enough to just add a   "version": "0.0.1", to the json file.

**Comment by pmorange** [comment]
Had to modify it by hand also.

**Comment by bjornsivertsen** [comment]
Hi @jmtatsch it has been fixed, and you can close the issue.

**Comment by jmtatsch** [comment]
Thank you.
