### ISSUE TITLE
Restoring state does not turn off lights that where off before launching animation

### ISSUE THREAD

**Issue by pmorange** [chazzu/hass-animated-scenes#5]
Hi,
All is said in the title :-)

If I have lights that are OFF before animating (they turn ON and animate if I set ignore_off: False), when I stop the animation they stay ON when they should logically return to their original OFF state.
Restore works for restoring state of already lit lights before an animation.

Anyway, I wanted to say thank you for this custom component.

**Comment by ggggut** [comment]
Hi @pmorange,

I had the same issue as you. It was actually pretty easy to fix. 
You need to edit `animated_scenes/__init__.py` and remove `and self.hass.states.get(light).state != 'off'` from line 109. 

So: 

```python
109        for light in lights:
110           if light not in self.stored_state and self.hass.states.get(light).state != 'off':
111                self.stored_state[light]: State = self.hass.states.get(light)
```


Turns to:

```python
109        for light in lights:
110            if light not in self.stored_state:
111                self.stored_state[light]: State = self.hass.states.get(light)
```

Reboot your core an voilà. 
The change allows the `off` state of the entity to be stored.

I don't know if it breaks other stuff though. Until now everything works as expected for me.

Better late than never :D

**Comment by bjornsivertsen** [comment]
Someone should fork it by now, with all these small fixes. :)

**Comment by chazzu** [comment]
i'm not sure if this counts as a fix per se. I did that on purpose because I figure if you turned on a light in the middle you may want it to stay on. Maybe an optional setting?

I promise I'm coming back to the project soon.

**Comment by pmorange** [comment]
@ggggut  Many thanks for this simple fix.
@chazzu  thanks for the efforts and all the good work :-)

**Comment by chazzu** [comment]
added restore_power option in commit 3b62c71e7aecddd3a960eeffa6999337e41e4b09 which should cover this use case

**Comment by cibrenvenuti** [comment]
Hi @chazzu and merry Christmas ☺️
I have same issue of OP, when I switch off the animation none of my lights wont to restore their original state: colors and Power on/off, none. What could be the problem?

Thanks a lot in advance
