### ISSUE TITLE
Component error: animated_scenes - Integration 'animated_scenes' not found.

### ISSUE THREAD

**Issue by mortalone** [chazzu/hass-animated-scenes#9]
i have downloaded the files.
put them in folder "\\HOMEASSISTANT\config\custom_components\animated_scenes"

and rebooted the entire machine. but it seems like the integration is not running.

![screenshot_20210918_162503](https://user-images.githubusercontent.com/615637/133892142-3c25a8cb-a80d-4e08-9701-7ad9fa139304.jpg)

i get this error "Component error: animated_scenes - Integration 'animated_scenes' not found."

**Comment by bjornsivertsen** [comment]
Did you add the versioning to the manifest, as described here?
https://github.com/chazzu/hass-animated-scenes/issues/4

**Comment by mortalone** [comment]
Thank you. that fixed the problem.
